# 路径配置
paths:
  raw_data: "data/raw/demo_1000.parquet"
  processed_dir: "data/processed"
  mapping_path: "data/id_mapping.json"
  model_save_path: "checkpoints/best_model.pth"

# 硬件与环境 (A10 建议设为 cuda)
env:
  device: "cuda"  # 或者 "cpu"
  use_bf16: true  # A10 开启 bfloat16 加速

# 模型超参数 (针对 A10 完全体配置)
model:
  embed_dim: 256        # 维度从 16 直接拉到 256，增强特征表达
  num_layers: 4         # 可以稍微加深 Transformer 层数
  n_heads: 8
  dropout: 0.1          # 数据量大时，dropout 可以设小一点

train:
  batch_size: 512       # A10 建议从 512 起步，如果显存还空就翻倍到 1024
  lr: 0.0005            # Batch Size 变大后，学习率可以稍微调高一点（遵循线性缩放原则）
  epochs: 100
  positive_label: 2

# 预处理开关
preprocess:
  sample_ratio: 1.0  # 全量训练设为 1.0
  val_split: 0.2